In [2]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
ar1

array(6)

In [4]:
ar2=np.array([1,2,3,4,5])

In [5]:
ar2

array([1, 2, 3, 4, 5])

In [6]:
zero_array=np.zeros(2)

In [7]:
zero_array

array([0., 0.])

In [5]:
ar4=np.arange(2,15,2)

In [6]:
ar4


array([ 2,  4,  6,  8, 10, 12, 14])

In [9]:
ar5=np.transpose(ar4)

In [11]:
ar5

array([ 2,  4,  6,  8, 10, 12, 14])

In [10]:
ar6=np.ravel(ar5)

In [12]:
ar6

array([ 2,  4,  6,  8, 10, 12, 14])

In [7]:
a1=np.array([1,2])
a2=np.array([4,5])

In [8]:
a1

array([1, 2])

In [9]:
a2

array([4, 5])

In [15]:
concat=np.concatenate((a1,a2))

In [16]:
concat

array([1, 2, 4, 5])

In [10]:
hori=np.vstack((a1,a2))

In [11]:
hori

array([[1, 2],
       [4, 5]])

In [21]:
mat1=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[6,7,5,8]])
print(mat1)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]
 [6 7 5 8]]


In [22]:
det_of_mat=np.linalg.det(mat1)

In [23]:
det_of_mat

3.197442310920453e-15

In [26]:
inverse=np.linalg.inv(mat1)

In [27]:
inverse

array([[-3.12749974e+15,  6.25499948e+15, -3.12749974e+15,
         8.33333333e-02],
       [ 4.37849964e+15, -8.75699928e+15,  4.37849964e+15,
         8.33333333e-02],
       [ 6.25499948e+14, -1.25099990e+15,  6.25499948e+14,
        -4.16666667e-01],
       [-1.87649984e+15,  3.75299969e+15, -1.87649984e+15,
         2.50000000e-01]])

In [28]:
dense=np.array([[1,0,3,0],[0,0,0,6],[0,6,7,8],[0,0,1,1]])

In [29]:
dense

array([[1, 0, 3, 0],
       [0, 0, 0, 6],
       [0, 6, 7, 8],
       [0, 0, 1, 1]])

In [30]:
from scipy.sparse import csr_matrix

In [31]:
sparse=csr_matrix(dense)

In [32]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [33]:
print(sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 3)	6
  (2, 1)	6
  (2, 2)	7
  (2, 3)	8
  (3, 2)	1
  (3, 3)	1
